REVOKE ALL PRIVILEGES ON TABLE "public"."JobExecution" FROM "anon", "authenticated";
REVOKE ALL PRIVILEGES ON TABLE "public"."LeadDiscoveryRecord" FROM "anon", "authenticated";
REVOKE ALL PRIVILEGES ON TABLE "public"."LeadEnrichmentRecord" FROM "anon", "authenticated";
REVOKE ALL PRIVILEGES ON TABLE "public"."OutboxEvent" FROM "anon", "authenticated";
REVOKE ALL PRIVILEGES ON TABLE "public"."TrainingRun" FROM "anon", "authenticated";
REVOKE ALL PRIVILEGES ON TABLE "public"."TrainingLabel" FROM "anon", "authenticated";
REVOKE ALL PRIVILEGES ON TABLE "public"."ModelVersion" FROM "anon", "authenticated";
REVOKE ALL PRIVILEGES ON TABLE "public"."ModelEvaluation" FROM "anon", "authenticated";
REVOKE ALL PRIVILEGES ON TABLE "public"."AnalyticsDailyRollup" FROM "anon", "authenticated";
REVOKE ALL PRIVILEGES ON TABLE "public"."IcpProfile" FROM "anon", "authenticated";
REVOKE ALL PRIVILEGES ON TABLE "public"."QualificationRule" FROM "anon", "authenticated";
REVOKE ALL PRIVILEGES ON TABLE "public"."app_admins" FROM "anon", "authenticated";
REVOKE ALL PRIVILEGES ON TABLE "public"."businesses" FROM "anon", "authenticated";
REVOKE ALL PRIVILEGES ON TABLE "public"."business_contacts" FROM "anon", "authenticated";
REVOKE ALL PRIVILEGES ON TABLE "public"."business_conversions" FROM "anon", "authenticated";
REVOKE ALL PRIVILEGES ON TABLE "public"."business_evidence" FROM "anon", "authenticated";
REVOKE ALL PRIVILEGES ON TABLE "public"."contact_recovery_items" FROM "anon", "authenticated";
REVOKE ALL PRIVILEGES ON TABLE "public"."discovery_cost_events" FROM "anon", "authenticated";
REVOKE ALL PRIVILEGES ON TABLE "public"."job_runs" FROM "anon", "authenticated";
REVOKE ALL PRIVILEGES ON TABLE "public"."lead_pipeline_events" FROM "anon", "authenticated";
REVOKE ALL PRIVILEGES ON TABLE "public"."lead_rejections" FROM "anon", "authenticated";
REVOKE ALL PRIVILEGES ON TABLE "public"."manager_recommendation_records" FROM "anon", "authenticated";
REVOKE ALL PRIVILEGES ON TABLE "public"."pipeline_settings" FROM "anon", "authenticated";
REVOKE ALL PRIVILEGES ON TABLE "public"."search_tasks" FROM "anon", "authenticated";
REVOKE ALL PRIVILEGES ON TABLE "public"."sources" FROM "anon", "authenticated";
REVOKE ALL PRIVILEGES ON TABLE "public"."job_requests" FROM "anon", "authenticated";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON FUNCTIONS FROM "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON FUNCTIONS FROM "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON TABLES FROM "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON TABLES FROM "authenticated";
