import type {
  DemoAnalyticsDashboardSnapshot,
  DemoOperationsDashboardSnapshot,
} from './demo-dashboard-types.js';
import {
  DEMO_NARRATIVE_VERSION,
  DEMO_OPERATING_MONTHS,
  DEMO_OPERATING_TOTALS,
  DEMO_REPORTING_PERIOD,
  DEMO_SNAPSHOT_GENERATED_AT,
} from './demo-operating-narrative.js';

const formatCount = (value: number) => value.toLocaleString('en-US');
const june = DEMO_OPERATING_MONTHS[0]!;
const july = DEMO_OPERATING_MONTHS[1]!;

export const DEMO_OPERATIONS_DASHBOARD_SNAPSHOT: DemoOperationsDashboardSnapshot = {
  id: 'demo-dashboard-operations-2026-08',
  workspaceSlug: 'leadzilla-recruiter-demo',
  version: DEMO_NARRATIVE_VERSION,
  kind: 'operations',
  generatedAt: DEMO_SNAPSHOT_GENERATED_AT,
  headline: {
    title: 'Operations',
    eyebrow: 'Operations',
    summary: `Discovery, scoring, review, and historical outcomes across ${DEMO_REPORTING_PERIOD}.`,
    status: 'Two-month operating view',
  },
  metrics: [
    {
      id: 'source-inventory',
      label: 'Database leads',
      value: formatCount(DEMO_OPERATING_TOTALS.sourceRecords),
      unit: 'leads',
      detail: 'A curated two-month lead inventory for the recruiter-demo workspace.',
      tone: 'teal',
    },
    {
      id: 'discovered-leads',
      label: 'Screened universe',
      value: formatCount(DEMO_OPERATING_TOTALS.screened),
      unit: 'leads',
      detail: 'Active, non-deleted database leads in the screening population.',
      tone: 'green',
    },
    {
      id: 'enriched-scored',
      label: 'Scored profiles',
      value: formatCount(DEMO_OPERATING_TOTALS.scored),
      unit: 'profiles',
      detail: 'Businesses with enough public context to receive a Leadzilla fit score.',
      tone: 'blue',
    },
    {
      id: 'drafts-generated',
      label: 'AI drafts generated',
      value: formatCount(DEMO_OPERATING_TOTALS.drafts),
      unit: 'drafts',
      detail: 'OpenAI-assisted outreach drafts prepared for operator review.',
      tone: 'purple',
    },
    {
      id: 'pending-review',
      label: 'Pending review',
      value: formatCount(DEMO_OPERATING_TOTALS.pendingReview),
      unit: 'drafts',
      detail: `${DEMO_OPERATING_TOTALS.overdueReview} drafts are older than the 24-hour review target.`,
      tone: 'amber',
    },
  ],
  pipeline: [
    {
      id: 'discover',
      label: 'Discover',
      count: DEMO_OPERATING_TOTALS.screened,
      displayValue: formatCount(DEMO_OPERATING_TOTALS.screened),
      caption: 'SERP discovery and dedupe',
      status: 'Ready',
      health: 'healthy',
    },
    {
      id: 'enrich',
      label: 'Enrich',
      count: DEMO_OPERATING_TOTALS.scored,
      displayValue: formatCount(DEMO_OPERATING_TOTALS.scored),
      caption: 'Contacts, domains, and business context',
      status: 'Ready',
      health: 'healthy',
    },
    {
      id: 'score',
      label: 'Score',
      count: DEMO_OPERATING_TOTALS.scored,
      displayValue: formatCount(DEMO_OPERATING_TOTALS.scored),
      caption: 'Model and rule-based lead fit',
      status: 'Ready',
      health: 'healthy',
    },
    {
      id: 'draft',
      label: 'Draft',
      count: DEMO_OPERATING_TOTALS.drafts,
      displayValue: formatCount(DEMO_OPERATING_TOTALS.drafts),
      caption: 'OpenAI-assisted message generation',
      status: 'Ready',
      health: 'healthy',
    },
    {
      id: 'review',
      label: 'Review',
      count: DEMO_OPERATING_TOTALS.drafts - DEMO_OPERATING_TOTALS.pendingReview,
      displayValue: formatCount(DEMO_OPERATING_TOTALS.drafts - DEMO_OPERATING_TOTALS.pendingReview),
      caption: `${DEMO_OPERATING_TOTALS.pendingReview} drafts remain in the operator queue`,
      status: `${(((DEMO_OPERATING_TOTALS.drafts - DEMO_OPERATING_TOTALS.pendingReview) / DEMO_OPERATING_TOTALS.drafts) * 100).toFixed(1)}% reviewed`,
      health: 'healthy',
    },
  ],
  queues: [
    {
      id: 'discovery-capacity',
      label: 'Discovery capacity',
      value: 'Live when available',
      detail: 'Bounded discovery is exposed only when the isolated demo backend is online.',
    },
    {
      id: 'draft-generation',
      label: 'Draft generation',
      value: 'Live when available',
      detail: 'Draft generation is exposed only when the isolated demo backend is online.',
    },
    {
      id: 'review-queue',
      label: 'Review queue',
      value: `${DEMO_OPERATING_TOTALS.pendingReview} waiting`,
      detail: `${DEMO_OPERATING_TOTALS.overdueReview} drafts are older than 24 hours; delivery remains disabled.`,
    },
  ],
  systemHealth: [
    {
      id: 'edge-api',
      label: 'Dashboard data',
      status: 'Bundled',
      detail: 'The two-month recruiter workspace remains available without live service dependencies.',
      tone: 'green',
    },
    {
      id: 'openai-drafting',
      label: 'OpenAI drafting',
      status: 'Live only',
      detail: 'Drafting is available only after the isolated demo backend accepts a live session.',
      tone: 'purple',
    },
    {
      id: 'discovery-provider',
      label: 'Discovery provider',
      status: 'Live only',
      detail: 'Small discovery jobs require a healthy isolated demo backend.',
      tone: 'teal',
    },
    {
      id: 'outbound-delivery',
      label: 'Outbound delivery',
      status: 'Disabled',
      detail: 'Email, SMS, WhatsApp, provider delivery, follow-ups, and message.send remain blocked.',
      tone: 'amber',
    },
  ],
  recentRuns: [
    {
      id: 'demo-run-2026-06-premium-services',
      title: 'June · Initial scored inventory',
      status: 'Complete',
      found: june.sourceRecords,
      converted: june.scored,
      detail: `${formatCount(june.scored)} scored and ${formatCount(june.priority)} high-priority leads in the initial operating cohort.`,
    },
    {
      id: 'demo-run-2026-07-education-events',
      title: 'July · ICP expansion and review',
      status: 'Complete',
      found: july.sourceRecords,
      converted: july.scored,
      detail: `${formatCount(july.scored)} scored and ${formatCount(july.priority)} high-priority leads in the latest completed month.`,
    },
  ],
  safety: {
    title: 'Demo safety boundary',
    status: 'Outbound delivery locked',
    detail:
      'Dashboard data remains available during backend outages. Email, SMS, WhatsApp, provider delivery calls, follow-up delivery, and message.send publishing are disabled.',
  },
};

export const DEMO_ANALYTICS_DASHBOARD_SNAPSHOT: DemoAnalyticsDashboardSnapshot = {
  id: 'demo-dashboard-analytics-2026-08',
  workspaceSlug: 'leadzilla-recruiter-demo',
  version: DEMO_NARRATIVE_VERSION,
  kind: 'analytics',
  generatedAt: DEMO_SNAPSHOT_GENERATED_AT,
  headline: {
    title: 'Analytics Dashboard',
    eyebrow: 'Curated GTM snapshot',
    summary:
      `Executive view of market coverage, lead quality, review throughput, and historical outcomes across ${DEMO_REPORTING_PERIOD}.`,
    status: 'Two-month operating view',
  },
  metrics: [
    {
      id: 'qualified-rate',
      label: 'Priority rate',
      value: `${((DEMO_OPERATING_TOTALS.priority / DEMO_OPERATING_TOTALS.scored) * 100).toFixed(1)}%`,
      detail: `${formatCount(DEMO_OPERATING_TOTALS.priority)} high-fit opportunities from ${formatCount(DEMO_OPERATING_TOTALS.scored)} scored leads.`,
      tone: 'teal',
    },
    {
      id: 'avg-fit-score',
      label: 'Average lead score',
      value: DEMO_OPERATING_TOTALS.averageScore.toFixed(2),
      detail: 'Weighted Leadzilla fit score across the scored profile population.',
      tone: 'purple',
    },
    {
      id: 'priority-leads',
      label: 'Priority leads',
      value: formatCount(DEMO_OPERATING_TOTALS.priority),
      detail: 'High-fit leads ready for immediate review and message drafting.',
      tone: 'green',
    },
    {
      id: 'filtered-out',
      label: 'Rejected',
      value: formatCount(DEMO_OPERATING_TOTALS.disqualified),
      detail: 'Database leads held in the separate rejected-review lane.',
      tone: 'amber',
    },
  ],
  leadFlow: {
    totalBusinesses: DEMO_OPERATING_TOTALS.screened,
    evaluated: DEMO_OPERATING_TOTALS.scored,
    outsideFlow: 0,
    qualified: DEMO_OPERATING_TOTALS.priority,
    notQualified: DEMO_OPERATING_TOTALS.disqualified,
    high: DEMO_OPERATING_TOTALS.highFit,
    medium: DEMO_OPERATING_TOTALS.mediumFit,
    low: DEMO_OPERATING_TOTALS.lowFit,
    unbanded: 0,
  },
  scoreBands: [
    {
      id: 'high',
      label: 'High fit',
      count: DEMO_OPERATING_TOTALS.highFit,
      percent: Math.round((DEMO_OPERATING_TOTALS.highFit / DEMO_OPERATING_TOTALS.scored) * 100),
      detail: 'Best accounts for immediate review and high-context drafting.',
      tone: 'green',
    },
    {
      id: 'medium',
      label: 'Medium fit',
      count: DEMO_OPERATING_TOTALS.mediumFit,
      percent: Math.round((DEMO_OPERATING_TOTALS.mediumFit / DEMO_OPERATING_TOTALS.scored) * 100),
      detail: 'Solid-fit businesses for segment-specific campaigns.',
      tone: 'amber',
    },
    {
      id: 'low',
      label: 'Low fit',
      count: DEMO_OPERATING_TOTALS.lowFit,
      percent: Math.round((DEMO_OPERATING_TOTALS.lowFit / DEMO_OPERATING_TOTALS.scored) * 100),
      detail: 'Lower-priority leads kept out of active outreach lanes.',
      tone: 'red',
    },
  ],
  icpPerformance: [
    {
      id: 'boutique-hotels-vacation-rentals',
      name: 'Boutique Hotels & Vacation Rentals',
      scored: 1240,
      avgScore: 0.700,
      qualifiedRate: 59,
      qualified: 728,
      insight: 'The largest priority cohort, with portfolio scale and visible guest-acquisition signals supporting focused operator follow-up.',
    },
    {
      id: 'commercial-solar-roofing-contractors',
      name: 'Commercial Solar & Roofing Contractors',
      scored: 1170,
      avgScore: 0.680,
      qualifiedRate: 57,
      qualified: 663,
      insight: 'A deep regional contractor cohort with high-value project signals and enough commercial context for territory-focused review.',
    },
    {
      id: 'b2b-saas-developer-platforms',
      name: 'B2B SaaS & Developer Platforms',
      scored: 1070,
      avgScore: 0.650,
      qualifiedRate: 55,
      qualified: 586,
      insight: 'Technical vendors form a balanced priority cohort for product-signal research and buying-committee messaging tests.',
    },
    {
      id: 'multi-location-dental-groups',
      name: 'Multi-Location Dental Groups',
      scored: 1048,
      avgScore: 0.640,
      qualifiedRate: 53,
      qualified: 551,
      insight: 'A selective healthcare-services segment where location growth and centralized operations support a measured regional motion.',
    },
  ],
  outcomeSummary: [
    {
      id: 'drafts',
      label: 'Drafts generated',
      value: formatCount(DEMO_OPERATING_TOTALS.drafts),
      detail: 'Actual OpenAI-assisted draft records in the demo database snapshot.',
    },
    {
      id: 'replies',
      label: 'Replies',
      value: formatCount(DEMO_OPERATING_TOTALS.replies),
      detail: 'Historical replies from the same two-month outreach cohort.',
    },
    {
      id: 'sent',
      label: 'Messages sent',
      value: formatCount(DEMO_OPERATING_TOTALS.sent),
      detail: 'Historical messages only; current demo delivery is disabled.',
    },
    {
      id: 'meetings',
      label: 'Meetings booked',
      value: formatCount(DEMO_OPERATING_TOTALS.meetings),
      detail: 'Confirmed meetings attributed to the historical reply cohort.',
    },
    {
      id: 'reply-rate',
      label: 'Reply rate',
      value: `${((DEMO_OPERATING_TOTALS.replies / DEMO_OPERATING_TOTALS.sent) * 100).toFixed(1)}%`,
      detail: 'Replies divided by historical delivered messages in the two-month cohort.',
    },
  ],
  recommendations: [
    {
      id: 'prioritize-product-led',
      title: 'Protect product-led review capacity',
      detail: '728 priority accounts make this the deepest immediate-review segment; clear the three overdue drafts before expanding volume.',
    },
    {
      id: 'expand-gtm-playbook',
      title: 'Expand the mid-market GTM playbook',
      detail: 'Mid-market GTM teams produced a 57% priority rate: 663 high-fit accounts from 1,170 scored profiles.',
    },
    {
      id: 'nurture-medium-fit',
      title: 'Build a measured medium-fit nurture lane',
      detail: '1,845 medium-fit leads provide enough depth for controlled copy testing without diluting the high-priority review queue.',
    },
  ],
  disqualificationReasons: [],
  safety: {
    title: 'Analytics snapshot',
    detail:
      'Metrics are intentionally stable for executive review. Outbound delivery remains disabled.',
  },
};
